# Generated by Django 3.0.3 on 2020-07-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200724_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Unavailable', 'Unavailable'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
